import "@radix-ui/themes/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { Box, Theme } from "@radix-ui/themes";
import { Providers } from "./_providers/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Theme
          accentColor="gray"
          grayColor="slate"
          scaling="110%"
          radius="large"
        >
          <Box>{children}</Box>
        </Theme>
      </body>
    </html>
  );
}
