import "@radix-ui/themes/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { Box, Theme } from "@radix-ui/themes";
import { Providers } from "@/providers";
import { ReactNode } from "react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Providers>
          <Theme
            accentColor="gray"
            grayColor="slate"
            scaling="110%"
            radius="large"
          >
            <Box className="appcontainer">
              <Header />
              {children}
              <Footer />
            </Box>
          </Theme>
        </Providers>
      </body>
    </html>
  );
}
